# Generated by Django 5.2.4 on 2025-07-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='price',
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.CharField(choices=[('1P', 'Cameră pentru 1 persoană'), ('2P', 'Cameră pentru 2 persoane'), ('3P', 'Cameră pentru 3 persoane'), ('APT', 'Apartament')], max_length=3),
        ),
    ]
