# Generated by Django 5.2.4 on 2025-07-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_reservation_price_reservation_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.CharField(choices=[('1P', 'Cameră pentru 1 persoană'), ('2P', 'Cameră pentru 2 persoane'), ('3P', 'Cameră pentru 3 persoane'), ('APT', 'Apartament')], editable=False, max_length=3),
        ),
    ]
