# Generated by Django 5.2.4 on 2025-07-28 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_reservation_room_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hotelreview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='hotelreview',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.reservation'),
        ),
        migrations.RemoveField(
            model_name='hotelreview',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotelreview',
            name='user',
        ),
    ]
