# Generated by Django 5.2.4 on 2025-07-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_hotel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
