# Generated by Django 5.2.4 on 2025-07-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_customuser_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
