# Generated by Django 5.2.4 on 2025-07-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_hotel_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reservation_deleted_notification',
            field=models.BooleanField(default=False),
        ),
    ]
