# Generated by Django 5.2.4 on 2025-08-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_reviewvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='hotels', to='booking.amenity'),
        ),
    ]
